[package]
name = "dash-mpd"
version = "0.13.1"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
description = "Parse, serialize, download an MPD manifest for MPEG-DASH or WebM-DASH media streaming"
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-rs"
license = "MIT"
keywords = ["video", "streaming", "MPD", "DASH", "MPEG"]
categories = ["multimedia", "multimedia::video", "parser-implementations"]
publish = true
edition = "2021"

[dependencies]
base64 = "0.21.2"
base64-serde = "0.7.0"
serde = { version = "1.0.185", features = ["derive"] }
serde_with = { version = "3.3.0", features = ["base64"] }
quick-xml = { version = "0.30.0", features = ["serialize", "overlapped-lists"] }
chrono = { version = "0.4.26", features = ["serde"] }
num-traits = "0.2.16"
iso8601 = "0.6.1"
regex = "1.9.3"
thiserror = "1.0.47"
fs-err = "2.9.0"
log = "0.4.20"
url = { version = "2.4.0", optional = true }
data-url = { version = "0.3.0", optional = true }
reqwest = { version = "0.11.20", default-features = false, optional = true }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "time"] }
backoff = { version = "0.4.0", features = ["tokio"], optional = true }
governor = { version = "0.6.0", optional = true }
xmltree = { version = "0.10.3", optional = true }
async-recursion = { version = "1.0.4", optional = true }
tempfile = { version = "3.8.0", optional = true }
sanitise-file-name = { version = "1.0.0", optional = true }
ac-ffmpeg = { version = "0.18.1", optional = true }
ffprobe = { version = "0.3.3", optional = true }

[dev-dependencies]
env_logger = "0.10.0"
sha2 = "0.10.7"
hex-literal = "0.4.1"
colored = "2.0.4"
indicatif = "0.17.6"
clap = "4.3.24"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "time", "macros"] }
axum = "0.6.20"
axum-server = { version = "0.5.1" }
anyhow = "1.0.75"
roxmltree = "0.18.0"
xmlem = "0.2.3"

[features]
default = ["fetch", "native-tls", "compression", "socks", "scte35"]
fetch = ["url", "data-url", "reqwest", "backoff", "governor", "xmltree", "async-recursion", "tempfile", "sanitise-file-name", "ffprobe"]
libav = ["ac-ffmpeg"]
scte35 = []
compression = ["reqwest/gzip"]
socks = ["reqwest/socks"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
trust-dns = ["reqwest/trust-dns"]

[target.'cfg(unix)'.dependencies]
xattr = "1.0"
