on: [push]

name: build

jobs:
  check:
    name: dash-mpd-rs check/nightly
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo check
      - run: cargo hack check --feature-powerset --no-dev-deps

  test:
    name: dash-mpd-rs test/stable
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev gpac
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
      - run: cargo run --example serialize
      - run: cargo run --example pprint_bbc_adaptive
