on: [push]

name: macos

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: taiki-e/install-action@cargo-hack

    - name: install GPAC/MP4Box
      run: |
           brew update
           brew install gpac

    - name: install ffmpeg
      run: |
           brew install ffmpeg

    - name: install Bento4 mp4decrypt
      run: |
        wget -q -O /tmp/bento4.zip https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-640.universal-apple-macosx.zip
        unzip /tmp/bento4.zip "Bento4-SDK-*/bin/mp4decrypt" -d /tmp
        sudo mv /tmp/Bento4-SDK*/bin/mp4decrypt /usr/local/bin

    - run: cargo hack check --feature-powerset --exclude-features libav --no-dev-deps
    - run: cargo build
    - run: cargo test --verbose --no-run
    - run: cargo test --verbose -- --show-output
