on: [push]

name: macos

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo build --verbose
    - run: cargo test --verbose --no-run
    - run: cargo test --verbose
