on: [push]

name: windows

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: taiki-e/install-action@cargo-hack

    # The executables installed by choco are not available on the PATH in the current shell.
    # In normal use you would restart your shell, but a GitHub action is all run in the same shell,
    # so we need to add to the path explicitly.
    - name: install GPAC/MP4Box
      run: |
         choco install gpac
         echo "C:\Program Files\GPAC" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # The ffmpeg executable is installed at C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg.exe
    # A shim is created at C:\ProgramData\chocolatey\bin\ffmpeg.exe.
    - name: install ffmpeg
      run: |
         choco install ffmpeg
         echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: install Bento4/mp4decrypt
      run: |
          C:\msys64\usr\bin\wget.exe -q -O bento4.zip https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-640.x86_64-microsoft-win32.zip
          unzip bento4.zip "Bento4-SDK-*/bin/mp4decrypt.exe"
          ren Bento4-SDK*/bin/mp4decrypt.exe C:\Program Files

    - run: cargo hack check --feature-powerset --exclude-features libav --no-dev-deps
    - run: cargo build
    - run: cargo test --verbose --no-run
    - run: cargo test -- --show-output
