on: [push]

name: windows

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: taiki-e/install-action@cargo-hack
    - run: cargo hack check --feature-powerset --exclude-features libav --no-dev-deps
    - run: cargo build --verbose
    - run: cargo test --verbose --no-run
    - run: cargo test --verbose
